mindmap
  root((Participant))
        voit
            Les stands d'enregistrement
            L'application ou la plateforme de suivi
        dit
            "Je suis impatient de participer à IT Wave !"
            "Où dois-je m'enregistrer ?"
            "J'espère ne rien manquer d'important."
        fait
            S'enregistre pour l'événement
            Participe aux sessions et activités
            Fournit des retours d'expérience
   