 mindmap
 root((Manager Scolaire))
        voit
            Les participants s'enregistrer
            Les rapports de présence
        dit
            "Nous avons besoin de rapports de présence précis."
            "Je veux que l'événement reflète bien l'école."
            "Assurons-nous que les participants aient une bonne expérience."
        fait
            Surveille le déroulement de l'événement
            Examine les données des participants
            Résout les problèmes pendant l'événement
